name: wifi_p2p_demo_app
description: A Wi-Fi Direct Demo Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  flutter_p2p_plus:
    git:
      url: https://github.com/JAICHANGPARK/flutter_p2p_plus.git
      ref: main

  permission_handler: any
  lottie: any
  shared_preferences: any
  freezed_annotation: any
  json_annotation: ^4.4.0
  go_router: ^3.0.3

  flutter_riverpod: ^2.0.0-dev.4

  fluttertoast: any

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: any
  json_serializable: ^6.1.4

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
